### ISSUE TITLE
error, when compile

### ISSUE THREAD

**Issue by lexasub** [HRZNStudio/Spatial#37]
$ spatial worker build

Generating bridge settings for ChunkWorker.
Generating bridge settings for HorizonClientWorker.
Generating bridge settings for HorizonJavaWorker.
No changes detected, skipping code generation.
Running task 'build' for 'ChunkWorker'
[1/2] > Build Codegen
  [1/2] > Codegen Dependencies
  [1/2] < Codegen Dependencies (20ms)
  [2/2] > Codegen Java
No changes detected, skipping code generation.
  [2/2] < Codegen Java (40ms)
[1/2] < Build Codegen (60ms)
[2/2] > Build Gradle

FAILURE: Build failed with an exception.

* Where:
Build file 'expanse/workers/java/worker/build.gradle' line: 14

* What went wrong:
A problem occurred evaluating project ':worker'.
> org.gradle.api.internal.TaskOutputsInternal.dir(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskOutputs;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Encountered an error running command: 'gradle' with arguments 'jar linux_assembly windows_assembly macOS_assembly': exit status 1
Please make sure the step 'Gradle' defined in file 'expanse/workers/java/spatialos.java.build.json' is configured correctly.
[2/2] x Build Gradle (1.89s)
error: exit status 1
failed (1.95s)
Error during command execution: exit status 1
'spatial worker build' failed (2.0s)
Encountered an error during command execution.
    exit status 1

**Comment by Bluexin** [comment]
This project is stopped.
(as explained in more details by mail)
